#Mae, aca pondremos los tipos de datos

from enum import Enum, auto

class TiposDato(Enum):

    ASIGNACION = auto()
    AUXILIAR = auto()
    BIFURCACION = auto()
    BLOQUE_INSTRUCCIONES = auto()
    BOOLEANO = auto()
    COMPARACION = auto()
    COMPARADOR = auto()
    CONDICION = auto()
    DEF_FUNCION = auto()
    ELIF = auto()
    ELSE = auto()
    ENTERO = auto()
    ERROR = auto()
    EXPRESION_MATEMATICA = auto()
    VARIABLE_MATEMATICA = auto()
    FLOTANTE = auto()
    FUNCION = auto()
    IDENTIFICADOR = auto()
    IF = auto()
    INSTRUCCION = auto()
    INVOCACION = auto()
    NULO = auto()
    NUMERO = auto()
    OPERADOR = auto()
    OPERADOR_LOGICO = auto()
    PALABRA_CLAVE = auto()
    PARAMETROS = auto()
    PARA_FUNCION = auto()
    PARA_INVOCACION = auto()
    PRINCIPAL = auto()
    PRINT = auto()
    PROGRAMA = auto()
    REPETICION = auto()  
    RETORNO = auto()
    TEXTO = auto()  
    VALOR_VERDAD = auto()